{{- if .Values.storage.pvEnabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.storage.pvName }}
  labels:
    type: nfs
spec:
  capacity:
    storage: {{ .Values.storage.size }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.storage.storageClassName }}
  nfs:
    server: {{ .Values.storage.nfs.server }}
    path: {{ .Values.storage.nfs.path }}
  mountOptions:
    - vers=3
    - rw
    - hard
    - timeo=600
    - retrans=5
{{- end }}
